project:
  type: website

website:
  title: "DxD"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: Productos
        menu: 
          - href: packages.qmd
            text: Paquetes
          - href: docker.qmd
            text: Docker

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

